try {
} catch (e if e instanceof Exception) {
} catch (e) {
} finally {
}
